# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(676, 372)
        MainWindow.setStyleSheet("background-color: rgb(34, 39, 49);\n"
"\n"
"width:100px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 90, 281, 28))
        self.pushButton.setStyleSheet("QPushButton{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"padding:2px 15px;\n"
"background-color: rgb(68, 87, 96);\n"
"border:2px solid rgb(123, 157, 190) ;\n"
"border-radius:10px;\n"
"color: rgb(179, 202, 207);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"border:2px solid  rgb(138, 176, 194);\n"
"border-radius:10px;\n"
"height:20px;\n"
"color: rgb(230, 248, 253);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"border:2px solid  rgb(93, 119, 131);\n"
"border-radius:10px;\n"
"height:20px;\n"
"color: rgb(230, 248, 253);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 90, 281, 28))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"padding:2px 15px;\n"
"background-color: rgb(68, 87, 96);\n"
"border:2px solid rgb(123, 157, 190) ;\n"
"border-radius:10px;\n"
"color: rgb(179, 202, 207);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"border:2px solid  rgb(138, 176, 194);\n"
"border-radius:10px;\n"
"height:20px;\n"
"color: rgb(230, 248, 253);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"border:2px solid  rgb(93, 119, 131);\n"
"border-radius:10px;\n"
"height:20px;\n"
"color: rgb(230, 248, 253);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 140, 281, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 141, 21))
        self.label_2.setStyleSheet("color: rgb(179, 202, 207);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 221, 21))
        self.label_3.setStyleSheet("color: rgb(179, 202, 207);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 191, 16))
        self.label_4.setStyleSheet("color: rgb(179, 202, 207);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, 130, 121, 16))
        self.label_5.setStyleSheet("color: rgb(179, 202, 207);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(370, 160, 151, 16))
        self.label_6.setStyleSheet("color: rgb(179, 202, 207);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(370, 190, 131, 16))
        self.label_7.setStyleSheet("color: rgb(179, 202, 207);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 731, 51))
        self.label_8.setStyleSheet("color: rgb(179, 202, 207);")
        self.label_8.setObjectName("label_8")
        self.kamera = QtWidgets.QLabel(self.centralwidget)
        self.kamera.setGeometry(QtCore.QRect(190, 290, 351, 20))
        self.kamera.setStyleSheet("color: rgb(179, 202, 207);")
        self.kamera.setObjectName("kamera")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(510, 190, 16, 16))
        self.label_11.setStyleSheet("color:blue;")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(520, 190, 16, 16))
        self.label_12.setStyleSheet("color:green;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(530, 160, 16, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(540, 160, 16, 16))
        self.label_14.setStyleSheet("color:green;")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(500, 130, 16, 16))
        self.label_15.setStyleSheet("color:red;")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(510, 130, 21, 16))
        self.label_16.setStyleSheet("color:green;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(110, 250, 471, 20))
        self.label_17.setStyleSheet("color: rgb(179, 202, 207);")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(210, 200, 16, 16))
        self.label_18.setStyleSheet("color:black;")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(220, 200, 16, 16))
        self.label_19.setStyleSheet("color:green;")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(130, 170, 16, 16))
        self.label_20.setStyleSheet("color:green;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(140, 170, 16, 16))
        self.label_21.setStyleSheet("color:red;")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(140, 140, 16, 16))
        self.label_22.setStyleSheet("color:green;")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(150, 140, 16, 16))
        self.label_23.setStyleSheet("color:blue;")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(90, 250, 16, 16))
        self.label_24.setStyleSheet("color:green;")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(70, 250, 16, 16))
        self.label_25.setStyleSheet("color:red;")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(50, 250, 16, 16))
        self.label_26.setStyleSheet("color:black;")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(30, 250, 16, 16))
        self.label_27.setStyleSheet("color:blue;")
        self.label_27.setObjectName("label_27")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 250, 16, 16))
        self.label_9.setStyleSheet("color:yellow;")
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 676, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Head Screen"))
        self.pushButton_2.setText(_translate("MainWindow", "Main Screen"))
        self.label_2.setText(_translate("MainWindow", "ScreenShot alabirsiniz"))
        self.label_3.setText(_translate("MainWindow", "Çift tık yapabilirsiniz"))
        self.label_4.setText(_translate("MainWindow", "Uygulamadan  Çıkış Yapabilirsiniz"))
        self.label_5.setText(_translate("MainWindow", "Tek tık yapabilirsiniz"))
        self.label_6.setText(_translate("MainWindow", "Mouse basılı tutabilirsiniz"))
        self.label_7.setText(_translate("MainWindow", "Sağ tık yapabilirsiniz"))
        self.label_8.setText(_translate("MainWindow", "NOT: Aşagıdaki butonlardan hangisini seçerseniz o butonun altındaki fonksiyonlar ile çalışabilirsiniz"))
        self.kamera.setText(_translate("MainWindow", "Kamera Butona Bastıktan Birkaç Saniye Sonra Açılacaktır"))
        self.label_11.setText(_translate("MainWindow", "o"))
        self.label_12.setText(_translate("MainWindow", "o"))
        self.label_13.setText(_translate("MainWindow", "o"))
        self.label_14.setText(_translate("MainWindow", "o"))
        self.label_15.setText(_translate("MainWindow", "o"))
        self.label_16.setText(_translate("MainWindow", "o"))
        self.label_17.setText(_translate("MainWindow", "Parmaklardaki hangi iki rengin mesafesin değiştiğinde çalşacak aksiyonu gösteriri"))
        self.label_18.setText(_translate("MainWindow", "o"))
        self.label_19.setText(_translate("MainWindow", "o"))
        self.label_20.setText(_translate("MainWindow", "o"))
        self.label_21.setText(_translate("MainWindow", "o"))
        self.label_22.setText(_translate("MainWindow", "o"))
        self.label_23.setText(_translate("MainWindow", "o"))
        self.label_24.setText(_translate("MainWindow", "o"))
        self.label_25.setText(_translate("MainWindow", "o"))
        self.label_26.setText(_translate("MainWindow", "o"))
        self.label_27.setText(_translate("MainWindow", "o"))
        self.label_9.setText(_translate("MainWindow", "o"))
